### PR TITLE
Fix expired Discord link

### PR DESCRIPTION
**Pull request by mcauser**

### CODE REVIEW

**Comment by dhalbert** [comment]
This needs a pylint fix.

**Comment by mcauser** [comment]
@dhalbert pylint fix in: https://github.com/adafruit/Adafruit_Python_Extended_Bus/pull/5

**Review by makermelissa — APPROVED** [review]
Thanks!

**Comment by wallarug** [comment]
Hi @makermelissa,

Can you please confirm / verify that all the PRs for the new discord link are correct?

I've noted that @mcauser has put in many PR changed across the whole of GitHub for this issue.  

I just want to be sure before allowing any of these changes into any of my CircuitPython Libs.

**Comment by makermelissa** [comment]
Yes @wallarug, the link is correct. I just verified by going to the link.

**Comment by wallarug** [comment]
Ok Thanks @makermelissa!  

Benefits of not being behind a school firewall 😅  is checking discord links.

**Comment by mcauser** [comment]
FYI, `https://adafru.it/discord` 302s to `https://discord.gg/5FBsBHU`, which is (Scott) tannewt's invite:

Screen Shot 2020-12-08 at 1 42 18 pm

Using the `https://adafru.it/discord` redirector is preferred over a `discord.gg/xyz` link so that when it expires, admins can simply swap in a new invite url and not update a few thousand readmes and references

**Pull request merged**
